version: '3'

services:
  db:
    container_name: mysql_db
    image: mysql:9.0.1-oracle
    volumes:
      - ./mysql-db:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  
  phpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:80"
    environment:
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
volumes:
    mysql-db:
      external: true  
    